// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLwXazUG8uPTqQ6tr1nqugiBFTUVAB2A',
    appId: '1:352156804018:web:b8fdc2d7b0d9833088faab',
    messagingSenderId: '352156804018',
    projectId: 'dtocodes',
    authDomain: 'dtocodes.firebaseapp.com',
    storageBucket: 'dtocodes.appspot.com',
    measurementId: 'G-0YJYE0VR7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bjJL3wtN9Nwp1Cx1f5iUm--CimK8E6c',
    appId: '1:352156804018:android:2c255b35c3eb022d88faab',
    messagingSenderId: '352156804018',
    projectId: 'dtocodes',
    storageBucket: 'dtocodes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1fOk-RFdQuzSIb6pjfSasUSJZqkOWTX4',
    appId: '1:352156804018:ios:138947a9de3c92a188faab',
    messagingSenderId: '352156804018',
    projectId: 'dtocodes',
    storageBucket: 'dtocodes.appspot.com',
    iosClientId: '352156804018-p591rmhltlogra330oruir56aocb2vgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneManagementDto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1fOk-RFdQuzSIb6pjfSasUSJZqkOWTX4',
    appId: '1:352156804018:ios:138947a9de3c92a188faab',
    messagingSenderId: '352156804018',
    projectId: 'dtocodes',
    storageBucket: 'dtocodes.appspot.com',
    iosClientId: '352156804018-p591rmhltlogra330oruir56aocb2vgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneManagementDto',
  );
}
